### ISSUE TITLE
"udp.errors.alreadyused"

### ISSUE THREAD

**Issue by chrisrock1984** [pierrecle/node-red-contrib-mi-devices#12]
hi,

I have two gateways running. When I deploy, this errors occurs:
msg : string[22]
"udp.errors.alreadyused"

msg : string[44]
"node-red-contrib-mi-devices:udp.errors.error"

Thanks!!

**Comment by bemble** [comment]
Thanks for the feedback.
I don’t 2 gateways for now. I‘ll take a look when possible (I'll get another gateway in few weeks, but I'll see if someone can lend one to me).
Gateway nodes are nearly copy/paste of udp nodes preconfigured as described
in node-red-contrib-xiaomi-devices.

**Comment by mkazlauskas** [comment]
I'm getting the same error with single gateway. It happens on first connection when I redeploy, so I assume it's because it doesn't properly disconnect the existing connection.

**Comment by bemble** [comment]
This should be solved in 2.0.0 with the completely rewritten gateway code with #21

**Comment by aidbish** [comment]
hi, getting the same issue with multiple gateways
Any idea when new version will be released

**Comment by bemble** [comment]
I'll release a beta soon version but, I will not probably go further myself, for 2 reasons: I don't use nodered anymore and I really don't have the time to go further for now.

**Comment by rolfz** [comment]
A pitty that this problem was not resolved, but for thoese who have a gateway node that does not connect anymore and a log showing this error, I just found that removing all Gateway nodes (not the filter) and reentering them after a "deploy" may fix the issue. It worked form me :-) and you do not loose the sensor confirguration with this exercice ! Error messages are still in the log, but Node-Red connects to the gateway correctly.

**Comment by MarcoBruh** [comment]
Any progress on this issue? I'm experiencing the same problem with my Xiaomi Mi Gateway in Hass.io Node-Red. Tryed reinstalling the xiaomi component, rebooting the node-red add-on and rebooting the entire hass.io server. No success. 

Cant connect to the gateway in Node-Red, altough it works in Home assistant itself.

**Comment by aidbish** [comment]
> Any progress on this issue? I'm experiencing the same problem with my Xiaomi Mi Gateway in Hass.io Node-Red. Tryed reinstalling the xiaomi component, rebooting the node-red add-on and rebooting the entire hass.io server. No success.
> 
> Cant connect to the gateway in Node-Red, altough it works in Home assistant itself.

doubtful. see response from owner above and on front page

⚠️ I will not go further because I don't use node-red anymore and I don't have the time, but feel free to fork, PR & so on. If you want to maintain this module, feel free to ask.
